/* auto-generated */
export const tokenValues = {
  "accessibility.focus.offset": "2px",
  "accessibility.focus.width": "3px",
  "appShell.aside.inlineWidth": "18rem",
  "appShell.navigation.inlineWidth": "16rem",
  "appShell.overlay.maxWidth": "22rem",
  "appShell.sidebar.inlineWidth": "20rem",
  "background.canvas": "#fff",
  "background.overlay": "rgba(255, 255, 255, .8)",
  "background.surface": "#dfe6e9",
  "background.surfaceRaised": "#CFD8DC",
  "background.surfaceSunken": "rgba(0, 0, 0, .1)",
  "border.default": "rgba(0, 0, 0, .1)",
  "border.focusRing": "#03A9F4",
  "border.strong": "rgba(0, 0, 0, .2)",
  "border.subtle": "rgba(0, 0, 0, .05)",
  "color.black": "#000",
  "color.black.05": "rgba(0, 0, 0, .05)",
  "color.black.10": "rgba(0, 0, 0, .1)",
  "color.black.20": "rgba(0, 0, 0, .2)",
  "color.black.30": "rgba(0, 0, 0, .3)",
  "color.black.40": "rgba(0, 0, 0, .4)",
  "color.black.50": "rgba(0, 0, 0, .5)",
  "color.black.60": "rgba(0, 0, 0, .6)",
  "color.black.70": "rgba(0, 0, 0, .7)",
  "color.black.80": "rgba(0, 0, 0, .8)",
  "color.black.90": "rgba(0, 0, 0, .9)",
  "color.blue.100": "#C5CAE9",
  "color.blue.100.text": "#000",
  "color.blue.200": "#9FA8DA",
  "color.blue.200.text": "#000",
  "color.blue.300": "#7986CB",
  "color.blue.300.text": "#000",
  "color.blue.400": "#5C6BC0",
  "color.blue.400.text": "#fff",
  "color.blue.50": "#EDE7F6",
  "color.blue.50.text": "#000",
  "color.blue.500": "#3F51B5",
  "color.blue.500.text": "#fff",
  "color.blue.600": "#3949AB",
  "color.blue.600.text": "#fff",
  "color.blue.700": "#303F9F",
  "color.blue.700.text": "#fff",
  "color.blue.800": "#283593",
  "color.blue.800.text": "#fff",
  "color.blue.900": "#1A237E",
  "color.blue.900.text": "#fff",
  "color.blueGrey.100": "#CFD8DC",
  "color.blueGrey.100.text": "#000",
  "color.blueGrey.200": "#B0BEC5",
  "color.blueGrey.200.text": "#000",
  "color.blueGrey.300": "#90A4AE",
  "color.blueGrey.300.text": "#000",
  "color.blueGrey.400": "#78909C",
  "color.blueGrey.400.text": "#000",
  "color.blueGrey.50": "#ECEFF1",
  "color.blueGrey.50.text": "#000",
  "color.blueGrey.500": "#607D8B",
  "color.blueGrey.500.text": "#000",
  "color.blueGrey.600": "#546E7A",
  "color.blueGrey.600.text": "#fff",
  "color.blueGrey.700": "#455A64",
  "color.blueGrey.700.text": "#fff",
  "color.blueGrey.800": "#37474F",
  "color.blueGrey.800.text": "#fff",
  "color.blueGrey.900": "#263238",
  "color.blueGrey.900.text": "#fff",
  "color.gray.100": "#F5F5F5",
  "color.gray.100.text": "#000",
  "color.gray.200": "#EEEEEE",
  "color.gray.200.text": "#000",
  "color.gray.300": "#E0E0E0",
  "color.gray.300.text": "#000",
  "color.gray.400": "#BDBDBD",
  "color.gray.400.text": "#000",
  "color.gray.50": "#FAFAFA",
  "color.gray.50.text": "#000",
  "color.gray.500": "#9E9E9E",
  "color.gray.500.text": "#000",
  "color.gray.600": "#757575",
  "color.gray.600.text": "#fff",
  "color.gray.700": "#616161",
  "color.gray.700.text": "#fff",
  "color.gray.800": "#424242",
  "color.gray.800.text": "#fff",
  "color.gray.900": "#212121",
  "color.gray.900.text": "#fff",
  "color.green.100": "#C8E6C9",
  "color.green.100.text": "#000",
  "color.green.200": "#A5D6A7",
  "color.green.200.text": "#000",
  "color.green.300": "#81C784",
  "color.green.300.text": "#000",
  "color.green.400": "#66BB6A",
  "color.green.400.text": "#000",
  "color.green.50": "#E8F5E9",
  "color.green.50.text": "#000",
  "color.green.500": "#4CAF50",
  "color.green.500.text": "#000",
  "color.green.600": "#43A047",
  "color.green.600.text": "#000",
  "color.green.700": "#388E3C",
  "color.green.700.text": "#000",
  "color.green.800": "#2E7D32",
  "color.green.800.text": "#fff",
  "color.green.900": "#1B5E20",
  "color.green.900.text": "#fff",
  "color.lightBlue.100": "#B3E5FC",
  "color.lightBlue.100.text": "#000",
  "color.lightBlue.200": "#81D4FA",
  "color.lightBlue.200.text": "#000",
  "color.lightBlue.300": "#4FC3F7",
  "color.lightBlue.300.text": "#000",
  "color.lightBlue.400": "#29B6F6",
  "color.lightBlue.400.text": "#fff",
  "color.lightBlue.50": "#E1F5FE",
  "color.lightBlue.50.text": "#000",
  "color.lightBlue.500": "#03A9F4",
  "color.lightBlue.500.text": "#fff",
  "color.lightBlue.600": "#039BE5",
  "color.lightBlue.600.text": "#fff",
  "color.lightBlue.700": "#0288D1",
  "color.lightBlue.700.text": "#fff",
  "color.lightBlue.800": "#0277BD",
  "color.lightBlue.800.text": "#fff",
  "color.lightBlue.900": "#01579B",
  "color.lightBlue.900.text": "#fff",
  "color.red.100": "#FFCDD2",
  "color.red.100.text": "#000",
  "color.red.200": "#EF9A9A",
  "color.red.200.text": "#000",
  "color.red.300": "#E57373",
  "color.red.300.text": "#000",
  "color.red.400": "#EF5350",
  "color.red.400.text": "#000",
  "color.red.50": "#FFEBEE",
  "color.red.50.text": "#000",
  "color.red.500": "#F44336",
  "color.red.500.text": "#000",
  "color.red.600": "#E53935",
  "color.red.600.text": "#000",
  "color.red.700": "#D32F2F",
  "color.red.700.text": "#fff",
  "color.red.800": "#C62828",
  "color.red.800.text": "#fff",
  "color.red.900": "#B71C1C",
  "color.red.900.text": "#fff",
  "color.teal.100": "#B2DFDB",
  "color.teal.100.text": "#000",
  "color.teal.200": "#80CBC4",
  "color.teal.200.text": "#000",
  "color.teal.300": "#4DB6AC",
  "color.teal.300.text": "#000",
  "color.teal.400": "#26A69A",
  "color.teal.400.text": "#000",
  "color.teal.50": "#E0F2F1",
  "color.teal.50.text": "#000",
  "color.teal.500": "#009688",
  "color.teal.500.text": "#000",
  "color.teal.600": "#00897B",
  "color.teal.600.text": "#000",
  "color.teal.700": "#00796B",
  "color.teal.700.text": "#fff",
  "color.teal.800": "#00695C",
  "color.teal.800.text": "#fff",
  "color.teal.900": "#004D40",
  "color.teal.900.text": "#fff",
  "color.white": "#fff",
  "color.white.05": "rgba(255, 255, 255, .05)",
  "color.white.10": "rgba(255, 255, 255, .1)",
  "color.white.20": "rgba(255, 255, 255, .2)",
  "color.white.30": "rgba(255, 255, 255, .3)",
  "color.white.40": "rgba(255, 255, 255, .4)",
  "color.white.50": "rgba(255, 255, 255, .5)",
  "color.white.60": "rgba(255, 255, 255, .6)",
  "color.white.70": "rgba(255, 255, 255, .7)",
  "color.white.80": "rgba(255, 255, 255, .8)",
  "color.white.90": "rgba(255, 255, 255, .9)",
  "components.badge.colors.blue.background": "#1A237E",
  "components.badge.colors.blue.border": "#283593",
  "components.badge.colors.blue.text": "rgba(255, 255, 255, .9)",
  "components.badge.colors.gray.background": "rgba(255, 255, 255, .1)",
  "components.badge.colors.gray.border": "rgba(255, 255, 255, .1)",
  "components.badge.colors.gray.text": "rgba(255, 255, 255, .8)",
  "components.badge.colors.green.background": "#1B5E20",
  "components.badge.colors.green.border": "#2E7D32",
  "components.badge.colors.green.text": "rgba(255, 255, 255, .9)",
  "components.badge.colors.orange.background": "#5E2E0C",
  "components.badge.colors.orange.border": "#7A3E11",
  "components.badge.colors.orange.text": "#FFC39E",
  "components.badge.colors.pink.background": "#5A163A",
  "components.badge.colors.pink.border": "#77214E",
  "components.badge.colors.pink.text": "#FFC4DF",
  "components.badge.colors.purple.background": "#35215E",
  "components.badge.colors.purple.border": "#452D79",
  "components.badge.colors.purple.text": "#D6C2FF",
  "components.badge.colors.red.background": "#B71C1C",
  "components.badge.colors.red.border": "#C62828",
  "components.badge.colors.red.text": "rgba(255, 255, 255, .9)",
  "components.badge.colors.yellow.background": "#4A3500",
  "components.badge.colors.yellow.border": "#5E4300",
  "components.badge.colors.yellow.text": "#FFD98A",
  "components.badge.count.background": "#D32F2F",
  "components.badge.count.border": "#D32F2F",
  "components.badge.count.borderRadius": "999px",
  "components.badge.count.dotSize": "0.5rem",
  "components.badge.count.minSize": "1rem",
  "components.badge.count.paddingInline": "0.25rem",
  "components.badge.count.text": "#fff",
  "components.badge.layout.iconGap": "0.25rem",
  "components.badge.size.medium.borderRadius": "1rem",
  "components.badge.size.medium.height": "1.5rem",
  "components.badge.size.medium.paddingInline": "0.5rem",
  "components.badge.size.small.borderRadius": "1rem",
  "components.badge.size.small.height": "1.25rem",
  "components.badge.size.small.paddingInline": "0.5rem",
  "components.badge.variant.danger.outline.background": "transparent",
  "components.badge.variant.danger.outline.border": "#F44336",
  "components.badge.variant.danger.outline.text": "#E57373",
  "components.badge.variant.danger.soft.background": "#B71C1C",
  "components.badge.variant.danger.soft.border": "#C62828",
  "components.badge.variant.danger.soft.text": "rgba(255, 255, 255, .9)",
  "components.badge.variant.danger.solid.background": "#F44336",
  "components.badge.variant.danger.solid.border": "#F44336",
  "components.badge.variant.danger.solid.text": "#000",
  "components.badge.variant.info.outline.background": "transparent",
  "components.badge.variant.info.outline.border": "#5C6BC0",
  "components.badge.variant.info.outline.text": "#4FC3F7",
  "components.badge.variant.info.soft.background": "#1A237E",
  "components.badge.variant.info.soft.border": "#283593",
  "components.badge.variant.info.soft.text": "rgba(255, 255, 255, .9)",
  "components.badge.variant.info.solid.background": "#3F51B5",
  "components.badge.variant.info.solid.border": "#3F51B5",
  "components.badge.variant.info.solid.text": "#fff",
  "components.badge.variant.neutral.outline.background": "transparent",
  "components.badge.variant.neutral.outline.border": "rgba(255, 255, 255, .3)",
  "components.badge.variant.neutral.outline.text": "rgba(255, 255, 255, .8)",
  "components.badge.variant.neutral.soft.background": "rgba(255, 255, 255, .1)",
  "components.badge.variant.neutral.soft.border": "rgba(255, 255, 255, .1)",
  "components.badge.variant.neutral.soft.text": "rgba(255, 255, 255, .8)",
  "components.badge.variant.neutral.solid.background": "#757575",
  "components.badge.variant.neutral.solid.border": "#757575",
  "components.badge.variant.neutral.solid.text": "#fff",
  "components.badge.variant.success.outline.background": "transparent",
  "components.badge.variant.success.outline.border": "#4CAF50",
  "components.badge.variant.success.outline.text": "#81C784",
  "components.badge.variant.success.soft.background": "#1B5E20",
  "components.badge.variant.success.soft.border": "#2E7D32",
  "components.badge.variant.success.soft.text": "rgba(255, 255, 255, .9)",
  "components.badge.variant.success.solid.background": "#4CAF50",
  "components.badge.variant.success.solid.border": "#4CAF50",
  "components.badge.variant.success.solid.text": "#000",
  "components.badge.variant.warning.outline.background": "transparent",
  "components.badge.variant.warning.outline.border": "#D89A00",
  "components.badge.variant.warning.outline.text": "#FFD98A",
  "components.badge.variant.warning.soft.background": "#4A3500",
  "components.badge.variant.warning.soft.border": "#5E4300",
  "components.badge.variant.warning.soft.text": "#FFD98A",
  "components.badge.variant.warning.solid.background": "#D89A00",
  "components.badge.variant.warning.solid.border": "#D89A00",
  "components.badge.variant.warning.solid.text": "#000",
  "components.button.font": "'Helvetica Neue', system-ui, sans-serif",
  "components.button.intent.constructive.background": "#66BB6A",
  "components.button.intent.constructive.hover": "#81C784",
  "components.button.intent.constructive.text": "#000",
  "components.button.intent.destructive.background": "#EF5350",
  "components.button.intent.destructive.hover": "#E57373",
  "components.button.intent.destructive.text": "#000",
  "components.button.intent.primary.background": "#5C6BC0",
  "components.button.intent.primary.hover": "#6c7ac6",
  "components.button.intent.primary.text": "#fff",
  "components.button.intent.secondary.background": "#BDBDBD",
  "components.button.intent.secondary.hover": "#E0E0E0",
  "components.button.intent.secondary.text": "#000",
  "components.button.padding": "0 1rem",
  "components.button.size.hero.borderRadius.fluid": "0.7vw",
  "components.button.size.hero.borderRadius.max": "1rem",
  "components.button.size.hero.borderRadius.min": ".5rem",
  "components.button.size.hero.fontSize.fluid": "0.4vw + 0.92rem",
  "components.button.size.hero.fontSize.max": "1.25rem",
  "components.button.size.hero.fontSize.min": "1rem",
  "components.button.size.hero.height.fluid": "1.3vw + 2.2rem",
  "components.button.size.hero.height.max": "4rem",
  "components.button.size.hero.height.min": "2.5rem",
  "components.button.size.hero.letterSpacing.fluid": "0.002vw + 0.0095em",
  "components.button.size.hero.letterSpacing.max": "0",
  "components.button.size.hero.letterSpacing.min": "0.01em",
  "components.button.size.hero.lineHeight.fluid": "0.25vw + 1.25rem",
  "components.button.size.hero.lineHeight.max": "1.5rem",
  "components.button.size.hero.lineHeight.min": "1.375rem",
  "components.button.size.hero.padding.iconOnly.inline.fluid": "0.9vw + 0.5rem",
  "components.button.size.hero.padding.iconOnly.inline.max": "1.25rem",
  "components.button.size.hero.padding.iconOnly.inline.min": "0.75rem",
  "components.button.size.hero.padding.inline.fluid": "1.8vw + 0.85rem",
  "components.button.size.hero.padding.inline.max": "3rem",
  "components.button.size.hero.padding.inline.min": "1.5rem",
  "components.button.size.large.borderRadius": ".5rem",
  "components.button.size.large.height": "3rem",
  "components.button.size.large.padding": "0 1.25rem",
  "components.button.size.large.padding.iconOnly": "0 1rem",
  "components.button.size.medium.borderRadius": ".5rem",
  "components.button.size.medium.height": "2.5rem",
  "components.button.size.medium.padding": "0 1rem",
  "components.button.size.medium.padding.iconOnly": "0 0.75rem",
  "components.button.size.small.borderRadius": ".5rem",
  "components.button.size.small.height": "2rem",
  "components.button.size.small.padding": "0 0.75rem",
  "components.button.size.small.padding.iconOnly": "0 0.5rem",
  "components.button.variant.link.constructive.hoverText": "#81C784",
  "components.button.variant.link.constructive.text": "#66BB6A",
  "components.button.variant.link.destructive.hoverText": "#E57373",
  "components.button.variant.link.destructive.text": "#EF5350",
  "components.button.variant.link.primary.hoverText": "#7986CB",
  "components.button.variant.link.primary.text": "#5C6BC0",
  "components.button.variant.link.secondary.hoverText": "#E0E0E0",
  "components.button.variant.link.secondary.text": "#BDBDBD",
  "components.button.variant.outline.constructive.borderColor": "#66BB6A",
  "components.button.variant.outline.constructive.text": "#66BB6A",
  "components.button.variant.outline.destructive.borderColor": "#EF5350",
  "components.button.variant.outline.destructive.text": "#EF5350",
  "components.button.variant.outline.primary.borderColor": "#5C6BC0",
  "components.button.variant.outline.primary.text": "#5C6BC0",
  "components.button.variant.outline.secondary.borderColor": "#BDBDBD",
  "components.button.variant.outline.secondary.text": "#BDBDBD",
  "components.card.badgeOffset.medium": "0.75rem",
  "components.card.badgeOffset.small": "0.5rem",
  "components.card.border": "rgba(255, 255, 255, .05)",
  "components.card.divider": "rgba(255, 255, 255, .05)",
  "components.card.dividerThickness": "1px",
  "components.card.layout.actionsGapLarge": "1rem",
  "components.card.layout.actionsGapMedium": "0.75rem",
  "components.card.layout.actionsGapSmall": "0.5rem",
  "components.card.layout.dividerInsetBlock": "0.75rem",
  "components.card.layout.dividerInsetInline": "1rem",
  "components.card.layout.headerGap": "0.5rem",
  "components.card.overlay.interactiveLayer": "2",
  "components.card.overlay.layer": "1",
  "components.card.padding.large": "1.5rem",
  "components.card.padding.medium": "1rem",
  "components.card.padding.small": "0.75rem",
  "components.card.radius.large": "2rem",
  "components.card.radius.medium": "1rem",
  "components.card.radius.none": "0",
  "components.card.radius.small": ".5rem",
  "components.card.shadow.large": "0 16px 36px rgba(0, 0, 0, 0.16)",
  "components.card.shadow.medium": "0 8px 24px rgba(0, 0, 0, 0.12)",
  "components.card.shadow.small": "0 2px 8px rgba(0, 0, 0, 0.08)",
  "components.card.surface.default": "#13171b",
  "components.card.surface.elevated": "rgba(255, 255, 255, .05)",
  "components.card.surface.subtle": "rgba(0, 0, 0, .05)",
  "components.checkbox.background": "rgba(255, 255, 255, .1)",
  "components.checkbox.border": "rgba(255, 255, 255, .3)",
  "components.checkbox.checkmark": "#fff",
  "components.checkbox.disabled.background": "rgba(255, 255, 255, .1)",
  "components.checkbox.disabled.border": "rgba(255, 255, 255, .1)",
  "components.checkbox.disabled.text": "rgba(255, 255, 255, .4)",
  "components.checkbox.size.large.borderRadius": ".25rem",
  "components.checkbox.size.large.boxSize": "1.5rem",
  "components.checkbox.size.medium.borderRadius": ".25rem",
  "components.checkbox.size.medium.boxSize": "1.25rem",
  "components.checkbox.size.small.borderRadius": ".25rem",
  "components.checkbox.size.small.boxSize": "1rem",
  "components.checkbox.validation.invalid.border": "#EF5350",
  "components.checkbox.validation.valid.border": "#66BB6A",
  "components.checkbox.validation.warning.border": "#29B6F6",
  "components.copyButton.background": "rgba(255, 255, 255, .2)",
  "components.copyButton.background.hover": "rgba(255, 255, 255, .1)",
  "components.copyButton.text": "rgba(0, 0, 0, .7)",
  "components.copyButton.text.hover": "#000",
  "components.field.description": "rgba(255, 255, 255, .7)",
  "components.field.error": "#EF5350",
  "components.field.indicator.optional": "rgba(255, 255, 255, .6)",
  "components.field.indicator.required": "#EF5350",
  "components.field.layout.gap": "0.5rem",
  "components.field.layout.inlineControlGap": "0.75rem",
  "components.field.layout.inlineRowGap": "0.25rem",
  "components.field.layout.labelGap": "0.25rem",
  "components.input.adornment": "rgba(255, 255, 255, .7)",
  "components.input.background": "rgba(255, 255, 255, .1)",
  "components.input.border": "rgba(255, 255, 255, .2)",
  "components.input.disabled.background": "rgba(255, 255, 255, .1)",
  "components.input.disabled.border": "rgba(255, 255, 255, .1)",
  "components.input.disabled.placeholder": "rgba(255, 255, 255, .4)",
  "components.input.disabled.text": "rgba(255, 255, 255, .5)",
  "components.input.layout.adornmentGap": "0.5rem",
  "components.input.placeholder": "rgba(255, 255, 255, .5)",
  "components.input.size.large.borderRadius": ".5rem",
  "components.input.size.large.height": "3rem",
  "components.input.size.large.paddingInline": "1.25rem",
  "components.input.size.medium.borderRadius": ".5rem",
  "components.input.size.medium.height": "2.5rem",
  "components.input.size.medium.paddingInline": "1rem",
  "components.input.size.small.borderRadius": ".5rem",
  "components.input.size.small.height": "2rem",
  "components.input.size.small.paddingInline": "0.75rem",
  "components.input.validation.invalid.border": "#EF5350",
  "components.input.validation.valid.border": "#66BB6A",
  "components.input.validation.warning.border": "#29B6F6",
  "components.link.background": "transparent",
  "components.link.font": "'Helvetica Neue', system-ui, sans-serif",
  "components.link.text": "#3949AB",
  "components.navbar.border.default": "rgba(255, 255, 255, .05)",
  "components.navbar.brand.text": "#fff",
  "components.navbar.container.gap": "1.5rem",
  "components.navbar.floating.marginBlock": "0.5rem",
  "components.navbar.floating.marginInline": "1rem",
  "components.navbar.height.large": "5rem",
  "components.navbar.height.medium": "4rem",
  "components.navbar.height.small": "3rem",
  "components.navbar.link.active.text": "#fff",
  "components.navbar.link.default.text": "#fff",
  "components.navbar.link.disabled.text": "rgba(255, 255, 255, .7)",
  "components.navbar.link.hover.text": "#fff",
  "components.navbar.link.padding": "0.5rem 0.75rem",
  "components.navbar.list.gap": "0.5rem",
  "components.navbar.maxWidth.full": "100%",
  "components.navbar.maxWidth.large": "80rem",
  "components.navbar.maxWidth.medium": "64rem",
  "components.navbar.maxWidth.small": "40rem",
  "components.navbar.maxWidth.xLarge": "90rem",
  "components.navbar.menu.background": "#263238",
  "components.navbar.menu.drawer.padding": "1.25rem",
  "components.navbar.menu.drawer.zIndex": "30",
  "components.navbar.menu.overlay.insetInline": "1rem",
  "components.navbar.menu.overlay.zIndex": "30",
  "components.navbar.menu.padding": "1rem",
  "components.navbar.menu.radius": "1rem",
  "components.navbar.padding.large": "1.5rem",
  "components.navbar.padding.medium": "1rem",
  "components.navbar.padding.none": "0",
  "components.navbar.padding.small": "0.75rem",
  "components.navbar.radius": "1rem",
  "components.navbar.shadow.large": "0 16px 36px rgba(0, 0, 0, 0.16)",
  "components.navbar.shadow.medium": "0 8px 24px rgba(0, 0, 0, 0.12)",
  "components.navbar.shadow.small": "0 2px 8px rgba(0, 0, 0, 0.08)",
  "components.navbar.surface.default": "#263238",
  "components.navbar.surface.elevated": "rgba(255, 255, 255, .05)",
  "components.navbar.surface.subtle": "#13171b",
  "components.navbar.surface.transparent": "transparent",
  "components.navbar.toggle.background": "#13171b",
  "components.navbar.toggle.border": "rgba(255, 255, 255, .05)",
  "components.navbar.toggle.minHeight": "2rem",
  "components.navbar.toggle.padding": "0 0.75rem",
  "components.navbar.toggle.radius": ".5rem",
  "components.navbar.toggle.text": "#fff",
  "components.navbar.zIndex": "20",
  "components.progressBar.layout.descriptionColor": "#757575",
  "components.progressBar.layout.gap": "0.5rem",
  "components.progressBar.layout.labelColor": "#212121",
  "components.progressBar.layout.trackBackground": "#EEEEEE",
  "components.progressBar.layout.valueColor": "#212121",
  "components.progressBar.radius.full": "999px",
  "components.progressBar.radius.large": "2rem",
  "components.progressBar.radius.medium": "1rem",
  "components.progressBar.radius.none": "0",
  "components.progressBar.radius.small": ".5rem",
  "components.progressBar.size.large.trackBlock": "0.625rem",
  "components.progressBar.size.large.verticalTrackBlock": "9rem",
  "components.progressBar.size.large.verticalTrackInline": "0.625rem",
  "components.progressBar.size.medium.trackBlock": "0.5rem",
  "components.progressBar.size.medium.verticalTrackBlock": "7.5rem",
  "components.progressBar.size.medium.verticalTrackInline": "0.5rem",
  "components.progressBar.size.small.trackBlock": "0.375rem",
  "components.progressBar.size.small.verticalTrackBlock": "6rem",
  "components.progressBar.size.small.verticalTrackInline": "0.375rem",
  "components.progressBar.variant.constructive.fill": "#66BB6A",
  "components.progressBar.variant.destructive.fill": "#EF5350",
  "components.progressBar.variant.primary.fill": "#5C6BC0",
  "components.progressBar.variant.secondary.fill": "#BDBDBD",
  "components.radio.background": "rgba(255, 255, 255, .1)",
  "components.radio.border": "rgba(255, 255, 255, .3)",
  "components.radio.disabled.background": "rgba(255, 255, 255, .1)",
  "components.radio.disabled.border": "rgba(255, 255, 255, .1)",
  "components.radio.disabled.dot": "rgba(255, 255, 255, .4)",
  "components.radio.dot": "#5C6BC0",
  "components.radio.layout.gap": "0.5rem",
  "components.radio.size.large.borderRadius": "2rem",
  "components.radio.size.large.borderWidth": "1px",
  "components.radio.size.large.dotSize": "0.75rem",
  "components.radio.size.large.outerSize": "1.5rem",
  "components.radio.size.medium.borderRadius": "2rem",
  "components.radio.size.medium.borderWidth": "1px",
  "components.radio.size.medium.dotSize": "0.5rem",
  "components.radio.size.medium.outerSize": "1.25rem",
  "components.radio.size.small.borderRadius": "2rem",
  "components.radio.size.small.borderWidth": "1px",
  "components.radio.size.small.dotSize": "0.5rem",
  "components.radio.size.small.outerSize": "1rem",
  "components.radio.validation.invalid.border": "#EF5350",
  "components.radio.validation.valid.border": "#66BB6A",
  "components.radio.validation.warning.border": "#29B6F6",
  "components.safetyButton.hold.background": "#424242",
  "components.safetyButton.hold.text": "#FAFAFA",
  "components.safetyButton.variant.constructive.fill": "#66BB6A",
  "components.safetyButton.variant.destructive.fill": "#EF5350",
  "components.safetyButton.variant.primary.fill": "#5C6BC0",
  "components.safetyButton.variant.secondary.fill": "#BDBDBD",
  "components.select.background": "rgba(255, 255, 255, .1)",
  "components.select.border": "rgba(255, 255, 255, .2)",
  "components.select.chevron": "rgba(255, 255, 255, .7)",
  "components.select.disabled.background": "rgba(255, 255, 255, .1)",
  "components.select.disabled.border": "rgba(255, 255, 255, .1)",
  "components.select.disabled.chevron": "rgba(255, 255, 255, .4)",
  "components.select.disabled.text": "rgba(255, 255, 255, .5)",
  "components.select.layout.chevronInsetInlineEnd": "0.75rem",
  "components.select.layout.paddingInlineEnd": "2.5rem",
  "components.select.size.large.borderRadius": ".5rem",
  "components.select.size.large.height": "3rem",
  "components.select.size.large.paddingInline": "1.25rem",
  "components.select.size.medium.borderRadius": ".5rem",
  "components.select.size.medium.height": "2.5rem",
  "components.select.size.medium.paddingInline": "1rem",
  "components.select.size.small.borderRadius": ".5rem",
  "components.select.size.small.height": "2rem",
  "components.select.size.small.paddingInline": "0.75rem",
  "components.select.validation.invalid.border": "#EF5350",
  "components.select.validation.valid.border": "#66BB6A",
  "components.select.validation.warning.border": "#29B6F6",
  "components.skeleton.pulse.background": "rgba(0, 0, 0, .1)",
  "components.skeleton.shimmer.band": "rgba(0, 0, 0, .04)",
  "components.skeleton.shimmer.base": "rgba(0, 0, 0, .02)",
  "components.skiplink.background": "#5C6BC0",
  "components.skiplink.borderRadius": ".5rem",
  "components.skiplink.font": "'Helvetica Neue', system-ui, sans-serif",
  "components.skiplink.text": "#fff",
  "components.skiplink.x": "1rem",
  "components.skiplink.y": "1rem",
  "components.syntaxHighlighter.attrName": "#00796B",
  "components.syntaxHighlighter.attrValue": "#2E7D32",
  "components.syntaxHighlighter.boolean": "#D32F2F",
  "components.syntaxHighlighter.comment": "rgba(0, 0, 0, .7)",
  "components.syntaxHighlighter.deleted": "#D32F2F",
  "components.syntaxHighlighter.font": "'Sometype Mono Variable', monospace",
  "components.syntaxHighlighter.function": "#0288D1",
  "components.syntaxHighlighter.inserted": "#2E7D32",
  "components.syntaxHighlighter.keyword": "#303F9F",
  "components.syntaxHighlighter.lineNumber": "rgba(0, 0, 0, .7)",
  "components.syntaxHighlighter.number": "#00796B",
  "components.syntaxHighlighter.operator": "#D32F2F",
  "components.syntaxHighlighter.property": "#37474F",
  "components.syntaxHighlighter.punctuation": "#546E7A",
  "components.syntaxHighlighter.string": "#2E7D32",
  "components.syntaxHighlighter.tag": "#303F9F",
  "components.syntaxHighlighter.text": "#000",
  "components.table.body.background": "#13171b",
  "components.table.border.color": "rgba(255, 255, 255, .05)",
  "components.table.border.radius": ".5rem",
  "components.table.border.width": "1px",
  "components.table.caption.color": "rgba(255, 255, 255, .7)",
  "components.table.caption.padding": "0.5rem 0",
  "components.table.density.comfortable.paddingAdjust": "0rem",
  "components.table.density.compact.paddingAdjust": "-0.25rem",
  "components.table.density.spacious.paddingAdjust": "0.25rem",
  "components.table.empty.actionOffset": "0.25rem",
  "components.table.empty.background": "#13171b",
  "components.table.empty.description": "rgba(255, 255, 255, .7)",
  "components.table.empty.gap": "0.5rem",
  "components.table.empty.minHeight": "8rem",
  "components.table.empty.title": "#fff",
  "components.table.foot.background": "#13171b",
  "components.table.header.background": "rgba(255, 255, 255, .05)",
  "components.table.header.color": "#fff",
  "components.table.row.disabled.background": "rgba(255, 255, 255, .1)",
  "components.table.row.disabled.color": "rgba(255, 255, 255, .7)",
  "components.table.row.hover.background": "rgba(255, 255, 255, .1)",
  "components.table.row.selected.background": "#1A237E",
  "components.table.row.striped.background": "rgba(255, 255, 255, .05)",
  "components.table.size.large.paddingBlock": "1rem",
  "components.table.size.large.paddingInline": "1.25rem",
  "components.table.size.medium.paddingBlock": "0.75rem",
  "components.table.size.medium.paddingInline": "1rem",
  "components.table.size.small.paddingBlock": "0.5rem",
  "components.table.size.small.paddingInline": "0.75rem",
  "components.table.surface.default.background": "#13171b",
  "components.table.surface.subtle.background": "rgba(255, 255, 255, .05)",
  "components.tabs.indicator.background": "#7986CB",
  "components.tabs.indicator.inset.medium": "0.5rem",
  "components.tabs.indicator.inset.small": "0.25rem",
  "components.tabs.indicator.radius": "999px",
  "components.tabs.indicator.shadow": "none",
  "components.tabs.indicator.size.large": "6px",
  "components.tabs.indicator.size.medium": "4px",
  "components.tabs.indicator.size.small": "2px",
  "components.tabs.indicator.transition.duration": "120ms",
  "components.tabs.indicator.transition.easing": "cubic-bezier(0.2, 0, 0, 1)",
  "components.tabs.list.background": "#13171b",
  "components.tabs.list.borderColor": "rgba(255, 255, 255, .05)",
  "components.tabs.list.borderWidth": "1px",
  "components.tabs.list.gap": "0.25rem",
  "components.tabs.list.padding": "0.25rem",
  "components.tabs.list.radius": ".5rem",
  "components.tabs.panel.background": "#13171b",
  "components.tabs.panel.borderColor": "transparent",
  "components.tabs.panel.borderWidth": "0",
  "components.tabs.panel.padding": "1rem",
  "components.tabs.panel.radius": ".5rem",
  "components.tabs.trigger.active.background": "transparent",
  "components.tabs.trigger.active.borderColor": "transparent",
  "components.tabs.trigger.active.color": "#fff",
  "components.tabs.trigger.active.fontWeight": "600",
  "components.tabs.trigger.active.shadow": "none",
  "components.tabs.trigger.background": "transparent",
  "components.tabs.trigger.borderColor": "transparent",
  "components.tabs.trigger.borderWidth": "1px",
  "components.tabs.trigger.color": "rgba(255, 255, 255, .7)",
  "components.tabs.trigger.disabled.color": "#9E9E9E",
  "components.tabs.trigger.disabled.opacity": "0.5",
  "components.tabs.trigger.fontWeight": "500",
  "components.tabs.trigger.height": "2.25rem",
  "components.tabs.trigger.hover.background": "rgba(255, 255, 255, .05)",
  "components.tabs.trigger.hover.color": "#FAFAFA",
  "components.tabs.trigger.paddingX": "0.75rem",
  "components.tabs.trigger.paddingY": "0.5rem",
  "components.tabs.trigger.radius": ".5rem",
  "components.tabs.trigger.shadow": "none",
  "components.textarea.background": "rgba(255, 255, 255, .1)",
  "components.textarea.border": "rgba(255, 255, 255, .2)",
  "components.textarea.disabled.background": "rgba(255, 255, 255, .1)",
  "components.textarea.disabled.border": "rgba(255, 255, 255, .1)",
  "components.textarea.disabled.placeholder": "rgba(255, 255, 255, .4)",
  "components.textarea.disabled.text": "rgba(255, 255, 255, .5)",
  "components.textarea.placeholder": "rgba(255, 255, 255, .5)",
  "components.textarea.size.large.borderRadius": ".5rem",
  "components.textarea.size.large.minHeight": "10rem",
  "components.textarea.size.large.padding": "1.25rem",
  "components.textarea.size.medium.borderRadius": ".5rem",
  "components.textarea.size.medium.minHeight": "8rem",
  "components.textarea.size.medium.padding": "1rem",
  "components.textarea.size.small.borderRadius": ".5rem",
  "components.textarea.size.small.minHeight": "6rem",
  "components.textarea.size.small.padding": "0.75rem",
  "components.textarea.validation.invalid.border": "#EF5350",
  "components.textarea.validation.valid.border": "#66BB6A",
  "components.textarea.validation.warning.border": "#29B6F6",
  "components.toggleSwitch.disabled.thumb": "rgba(255, 255, 255, .3)",
  "components.toggleSwitch.disabled.trackBackground": "rgba(255, 255, 255, .1)",
  "components.toggleSwitch.disabled.trackBorder": "rgba(255, 255, 255, .1)",
  "components.toggleSwitch.size.large.borderRadius": "2rem",
  "components.toggleSwitch.size.large.height": "2rem",
  "components.toggleSwitch.size.large.iconSize": "1.25rem",
  "components.toggleSwitch.size.large.padding": "0",
  "components.toggleSwitch.size.large.thumbSize": "2rem",
  "components.toggleSwitch.size.large.thumbTranslate": "2rem",
  "components.toggleSwitch.size.large.width": "4rem",
  "components.toggleSwitch.size.medium.borderRadius": "2rem",
  "components.toggleSwitch.size.medium.height": "1.75rem",
  "components.toggleSwitch.size.medium.iconSize": "1rem",
  "components.toggleSwitch.size.medium.padding": "0",
  "components.toggleSwitch.size.medium.thumbSize": "1.75rem",
  "components.toggleSwitch.size.medium.thumbTranslate": "1.75rem",
  "components.toggleSwitch.size.medium.width": "3.5rem",
  "components.toggleSwitch.size.small.borderRadius": "2rem",
  "components.toggleSwitch.size.small.height": "1.5rem",
  "components.toggleSwitch.size.small.iconSize": "0.75rem",
  "components.toggleSwitch.size.small.padding": "0",
  "components.toggleSwitch.size.small.thumbSize": "1.5rem",
  "components.toggleSwitch.size.small.thumbTranslate": "1.5rem",
  "components.toggleSwitch.size.small.width": "3rem",
  "components.toggleSwitch.track.background": "rgba(255, 255, 255, .1)",
  "components.toggleSwitch.track.background.hover": "rgba(255, 255, 255, .2)",
  "components.toggleSwitch.track.border": "rgba(255, 255, 255, .2)",
  "components.toggleSwitch.track.icon": "rgba(255, 255, 255, .7)",
  "components.toggleSwitch.validation.invalid.border": "#EF5350",
  "components.toggleSwitch.validation.valid.border": "#66BB6A",
  "components.toggleSwitch.validation.warning.border": "#29B6F6",
  "components.toggleSwitch.variant.constructive.thumb": "#66BB6A",
  "components.toggleSwitch.variant.destructive.thumb": "#EF5350",
  "components.toggleSwitch.variant.primary.thumb": "#5C6BC0",
  "components.toggleSwitch.variant.secondary.thumb": "#BDBDBD",
  "components.tooltip.arrow.size": "10px",
  "components.tooltip.background": "#212121",
  "components.tooltip.border.color": "#616161",
  "components.tooltip.border.width": "1px",
  "components.tooltip.maxWidth": "20rem",
  "components.tooltip.paddingX": "0.75rem",
  "components.tooltip.paddingY": "0.5rem",
  "components.tooltip.radius": ".5rem",
  "components.tooltip.shadow": "0 8px 24px rgba(0, 0, 0, 0.12)",
  "components.tooltip.text": "#fff",
  "components.tooltip.zIndex": "30",
  "duration.fast": "120ms",
  "duration.medium": "200ms",
  "duration.slow": "320ms",
  "easing.emphasized": "cubic-bezier(0.2, 0, 0, 1.2)",
  "easing.standard": "cubic-bezier(0.2, 0, 0, 1)",
  "focus.ring.color": "#03A9F4",
  "focus.ring.gap": "#fff",
  "focus.ring.offset": "2px",
  "focus.ring.width": "3px",
  "font.family.default": "'Helvetica Neue', system-ui, sans-serif",
  "font.family.display": "Georgia, serif",
  "font.family.mono": "'Sometype Mono Variable', monospace",
  "font.family.sans": "'Helvetica Neue', system-ui, sans-serif",
  "font.family.serif": "Georgia, serif",
  "font.style.italic": "italic",
  "font.style.normal": "normal",
  "font.weight": "300",
  "font.weight.bold": "700",
  "font.weight.medium": "500",
  "font.weight.regular": "400",
  "font.weight.semiBold": "600",
  "grid.columns.desktop": 12,
  "grid.columns.mobile": 4,
  "grid.columns.tablet": 8,
  "grid.container.contentMaxWidth": "80rem",
  "grid.container.maxWidth.lg": "80rem",
  "grid.container.maxWidth.md": "64rem",
  "grid.container.maxWidth.sm": "40rem",
  "grid.container.maxWidth.xl": "90rem",
  "grid.container.paddingInline.desktop": "2rem",
  "grid.container.paddingInline.mobile": "1rem",
  "grid.container.paddingInline.tablet": "1.5rem",
  "grid.gutter.desktop": "1.5rem",
  "grid.gutter.mobile": "1rem",
  "grid.gutter.tablet": "1.25rem",
  "grid.rowGap.desktop": "1.5rem",
  "grid.rowGap.mobile": "1rem",
  "grid.rowGap.tablet": "1.25rem",
  "icon.inverse": "#fff",
  "icon.primary": "#000",
  "icon.secondary": "rgba(0, 0, 0, .7)",
  "intent.constructive.background": "#66BB6A",
  "intent.constructive.hover": "#81C784",
  "intent.constructive.text": "#000",
  "intent.destructive.background": "#EF5350",
  "intent.destructive.hover": "#E57373",
  "intent.destructive.text": "#000",
  "intent.primary.background": "#5C6BC0",
  "intent.primary.hover": "#6c7ac6",
  "intent.primary.text": "#fff",
  "intent.secondary.background": "#BDBDBD",
  "intent.secondary.hover": "#E0E0E0",
  "intent.secondary.text": "#000",
  "layer.base": "0",
  "layer.modal": "50",
  "layer.overlay": "30",
  "layer.popover": "40",
  "layer.raised": "10",
  "layer.sticky": "20",
  "layout.breakpoint.desktop": "1024px",
  "layout.breakpoint.mobile": "0px",
  "layout.breakpoint.tablet": "768px",
  "layout.pageShell.aside.span.desktop": 3,
  "layout.pageShell.aside.span.mobile": "4",
  "layout.pageShell.aside.span.tablet": "8",
  "layout.pageShell.container.maxWidth": "80rem",
  "layout.pageShell.main.span.desktop": 9,
  "layout.pageShell.main.span.mobile": "4",
  "layout.pageShell.main.span.tablet": "8",
  "layout.site.margin": "1rem",
  "layout.site.maxWidth": "800px",
  "layout.site.padding": "0",
  "opacity.disabled": "0.5",
  "opacity.subtle": "0.75",
  "radius.large": "2rem",
  "radius.medium": "1rem",
  "radius.small": ".5rem",
  "radius.xLarge": "4rem",
  "radius.xSmall": ".25rem",
  "shadow.large": "0 16px 36px rgba(0, 0, 0, 0.16)",
  "shadow.medium": "0 8px 24px rgba(0, 0, 0, 0.12)",
  "shadow.small": "0 2px 8px rgba(0, 0, 0, 0.08)",
  "size.control.large.font": "1.125rem",
  "size.control.large.height": "3rem",
  "size.control.large.icon": "1.5rem",
  "size.control.large.paddingInline": "1.25rem",
  "size.control.medium.font": "1rem",
  "size.control.medium.height": "2.5rem",
  "size.control.medium.icon": "1.25rem",
  "size.control.medium.paddingInline": "1rem",
  "size.control.small.font": "0.875rem",
  "size.control.small.height": "2rem",
  "size.control.small.icon": "1rem",
  "size.control.small.paddingInline": "0.75rem",
  "space.0": "0",
  "space.1": "0.25rem",
  "space.10": "3rem",
  "space.11": "3.5rem",
  "space.12": "4rem",
  "space.14": "5rem",
  "space.16": "6rem",
  "space.2": "0.5rem",
  "space.20": "8rem",
  "space.24": "10rem",
  "space.3": "0.75rem",
  "space.4": "1rem",
  "space.5": "1.25rem",
  "space.6": "1.5rem",
  "space.7": "1.75rem",
  "space.8": "2rem",
  "space.9": "2.5rem",
  "text.destructive": "#D32F2F",
  "text.inverse": "#fff",
  "text.link": "#303F9F",
  "text.muted": "rgba(0, 0, 0, .7)",
  "text.primary": "#000",
  "text.secondary": "rgba(0, 0, 0, .7)",
  "text.success": "#388E3C",
  "typography.body.large.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1.125rem",
    "lineHeight": "1.5rem",
    "fontWeight": "400"
  },
  "typography.body.large.fontSize": "1.125rem",
  "typography.body.large.fontStyle": "normal",
  "typography.body.large.fontWeight": "400",
  "typography.body.large.letterSpacing": "0.01em",
  "typography.body.large.lineHeight": "1.5rem",
  "typography.body.medium.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1rem",
    "lineHeight": "1.375rem",
    "fontWeight": "400"
  },
  "typography.body.medium.fontSize": "1rem",
  "typography.body.medium.fontStyle": "normal",
  "typography.body.medium.fontWeight": "400",
  "typography.body.medium.letterSpacing": "0.01em",
  "typography.body.medium.lineHeight": "1.375rem",
  "typography.body.mediumItalic.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1rem",
    "lineHeight": "1.375rem",
    "fontWeight": "400"
  },
  "typography.body.mediumItalic.fontSize": "1rem",
  "typography.body.mediumItalic.fontStyle": "italic",
  "typography.body.mediumItalic.fontWeight": "400",
  "typography.body.mediumItalic.letterSpacing": "0.01em",
  "typography.body.mediumItalic.lineHeight": "1.375rem",
  "typography.body.mediumStrong.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1rem",
    "lineHeight": "1.375rem",
    "fontWeight": "600"
  },
  "typography.body.mediumStrong.fontSize": "1rem",
  "typography.body.mediumStrong.fontStyle": "normal",
  "typography.body.mediumStrong.fontWeight": "600",
  "typography.body.mediumStrong.letterSpacing": "0.01em",
  "typography.body.mediumStrong.lineHeight": "1.375rem",
  "typography.body.small.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "0.875rem",
    "lineHeight": "1.25rem",
    "fontWeight": "400"
  },
  "typography.body.small.fontSize": "0.875rem",
  "typography.body.small.fontStyle": "normal",
  "typography.body.small.fontWeight": "400",
  "typography.body.small.letterSpacing": "0.01em",
  "typography.body.small.lineHeight": "1.25rem",
  "typography.code.medium.font": {
    "fontFamily": "'Sometype Mono Variable', monospace",
    "fontSize": "0.875rem",
    "lineHeight": "1.25rem",
    "fontWeight": "400"
  },
  "typography.code.medium.fontSize": "0.875rem",
  "typography.code.medium.fontStyle": "normal",
  "typography.code.medium.fontWeight": "400",
  "typography.code.medium.letterSpacing": "0",
  "typography.code.medium.lineHeight": "1.25rem",
  "typography.code.small.font": {
    "fontFamily": "'Sometype Mono Variable', monospace",
    "fontSize": "0.8125rem",
    "lineHeight": "1.125rem",
    "fontWeight": "400"
  },
  "typography.code.small.fontSize": "0.8125rem",
  "typography.code.small.fontStyle": "normal",
  "typography.code.small.fontWeight": "400",
  "typography.code.small.letterSpacing": "0",
  "typography.code.small.lineHeight": "1.125rem",
  "typography.heading.displayLarge.font": {
    "fontFamily": "Georgia, serif",
    "fontSize": "1.5rem",
    "lineHeight": "2.25rem",
    "fontWeight": "700"
  },
  "typography.heading.displayLarge.fontSize": "1.5rem",
  "typography.heading.displayLarge.fontStyle": "normal",
  "typography.heading.displayLarge.fontWeight": "700",
  "typography.heading.displayLarge.letterSpacing": "0",
  "typography.heading.displayLarge.lineHeight": "2.25rem",
  "typography.heading.large.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1.5rem",
    "lineHeight": "2.25rem",
    "fontWeight": "700"
  },
  "typography.heading.large.fontSize": "1.5rem",
  "typography.heading.large.fontStyle": "normal",
  "typography.heading.large.fontWeight": "700",
  "typography.heading.large.letterSpacing": "0",
  "typography.heading.large.lineHeight": "2.25rem",
  "typography.heading.medium.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1.375rem",
    "lineHeight": "1.75rem",
    "fontWeight": "700"
  },
  "typography.heading.medium.fontSize": "1.375rem",
  "typography.heading.medium.fontStyle": "normal",
  "typography.heading.medium.fontWeight": "700",
  "typography.heading.medium.letterSpacing": "0",
  "typography.heading.medium.lineHeight": "1.75rem",
  "typography.heading.small.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1.25rem",
    "lineHeight": "1.5rem",
    "fontWeight": "700"
  },
  "typography.heading.small.fontSize": "1.25rem",
  "typography.heading.small.fontStyle": "normal",
  "typography.heading.small.fontWeight": "700",
  "typography.heading.small.letterSpacing": "0",
  "typography.heading.small.lineHeight": "1.5rem",
  "typography.heading.xSmall.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1rem",
    "lineHeight": "1.375rem",
    "fontWeight": "700"
  },
  "typography.heading.xSmall.fontSize": "1rem",
  "typography.heading.xSmall.fontStyle": "normal",
  "typography.heading.xSmall.fontWeight": "700",
  "typography.heading.xSmall.letterSpacing": "0.01em",
  "typography.heading.xSmall.lineHeight": "1.375rem",
  "typography.label.large.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1.125rem",
    "lineHeight": "1.5rem",
    "fontWeight": "500"
  },
  "typography.label.large.fontSize": "1.125rem",
  "typography.label.large.fontStyle": "normal",
  "typography.label.large.fontWeight": "500",
  "typography.label.large.letterSpacing": "0.01em",
  "typography.label.large.lineHeight": "1.5rem",
  "typography.label.medium.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "1rem",
    "lineHeight": "1.375rem",
    "fontWeight": "500"
  },
  "typography.label.medium.fontSize": "1rem",
  "typography.label.medium.fontStyle": "normal",
  "typography.label.medium.fontWeight": "500",
  "typography.label.medium.letterSpacing": "0.01em",
  "typography.label.medium.lineHeight": "1.375rem",
  "typography.label.small.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "0.875rem",
    "lineHeight": "1.125rem",
    "fontWeight": "500"
  },
  "typography.label.small.fontSize": "0.875rem",
  "typography.label.small.fontStyle": "normal",
  "typography.label.small.fontWeight": "500",
  "typography.label.small.letterSpacing": "0.02em",
  "typography.label.small.lineHeight": "1.125rem",
  "typography.label.smallItalic.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "0.875rem",
    "lineHeight": "1.125rem",
    "fontWeight": "400"
  },
  "typography.label.smallItalic.fontSize": "0.875rem",
  "typography.label.smallItalic.fontStyle": "italic",
  "typography.label.smallItalic.fontWeight": "400",
  "typography.label.smallItalic.letterSpacing": "0.02em",
  "typography.label.smallItalic.lineHeight": "1.125rem",
  "typography.label.smallStrong.font": {
    "fontFamily": "'Helvetica Neue', system-ui, sans-serif",
    "fontSize": "0.875rem",
    "lineHeight": "1.125rem",
    "fontWeight": "600"
  },
  "typography.label.smallStrong.fontSize": "0.875rem",
  "typography.label.smallStrong.fontStyle": "normal",
  "typography.label.smallStrong.fontWeight": "600",
  "typography.label.smallStrong.letterSpacing": "0.08em",
  "typography.label.smallStrong.lineHeight": "1.125rem",
  "zIndex.0": 0,
  "zIndex.10": 10,
  "zIndex.20": 20,
  "zIndex.30": 30,
  "zIndex.40": 40,
  "zIndex.50": 50
} as const;
export type TokenValuePath = keyof typeof tokenValues;
