/* eslint-disable react-refresh/only-export-components */
import {
  MenuCheckboxItem,
  MenuContent,
  MenuGroup,
  MenuItem,
  MenuItemIcon,
  MenuItemIndicator,
  MenuItemMeta,
  MenuItemText,
  MenuLabel,
  MenuRadioGroup,
  MenuRadioItem,
  MenuRoot,
  MenuSeparator,
  MenuSub,
  MenuSubContent,
  MenuSubTrigger,
  MenuViewport,
} from './components';

export const Menu = Object.assign(MenuRoot, {
  Root: MenuRoot,
  Content: MenuContent,
  Viewport: MenuViewport,
  Group: MenuGroup,
  Label: MenuLabel,
  Item: MenuItem,
  ItemText: MenuItemText,
  ItemIcon: MenuItemIcon,
  ItemMeta: MenuItemMeta,
  Separator: MenuSeparator,
  CheckboxItem: MenuCheckboxItem,
  RadioGroup: MenuRadioGroup,
  RadioItem: MenuRadioItem,
  ItemIndicator: MenuItemIndicator,
  Sub: MenuSub,
  SubTrigger: MenuSubTrigger,
  SubContent: MenuSubContent,
});

export {
  MenuCheckboxItem,
  MenuContent,
  MenuGroup,
  MenuItem,
  MenuItemIcon,
  MenuItemIndicator,
  MenuItemMeta,
  MenuItemText,
  MenuLabel,
  MenuRadioGroup,
  MenuRadioItem,
  MenuRoot,
  MenuSeparator,
  MenuSub,
  MenuSubContent,
  MenuSubTrigger,
  MenuViewport,
};

export type {
  MenuAlign,
  MenuCheckboxItemProps,
  MenuContentProps,
  MenuDir,
  MenuGroupProps,
  MenuItemIconProps,
  MenuItemIndicatorProps,
  MenuItemMetaProps,
  MenuItemProps,
  MenuItemTextProps,
  MenuLabelProps,
  MenuOrientation,
  MenuPlacement,
  MenuRadioGroupProps,
  MenuRadioItemProps,
  MenuRootProps,
  MenuSelectEvent,
  MenuSeparatorProps,
  MenuSubContentProps,
  MenuSubProps,
  MenuSubTriggerProps,
  MenuViewportProps,
} from './types';
