export type {
  PolymorphicProps,
  TabsActivationMode,
  TabsIndicatorInset,
  TabsIndicatorOwnProps,
  TabsIndicatorProps,
  TabsIndicatorSize,
  TabsListOwnProps,
  TabsListProps,
  TabsOrientation,
  TabsOwnProps,
  TabsPanelOwnProps,
  TabsPanelProps,
  TabsPanelsOwnProps,
  TabsPanelsProps,
  TabsProps,
  TabsRootProps,
  TabsTriggerOwnProps,
  TabsTriggerProps,
} from '@themeshift/headless/components/Tabs';
