import type { ComponentData } from './types';

export const componentData = [
  {
    apiReference: [
      {
        comments:
          'Accessible label for an icon-only button.\n\nRequired when using `icon` without visible text.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'aria-label',
        type: 'string',
        values: [],
      },
      {
        comments:
          'ID of the element that labels an icon-only button.\n\nRequired when using `icon` without visible text.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'aria-labelledby',
        type: 'string',
        values: [],
      },
      {
        comments:
          'Applies Button styles to a single child element instead of rendering a native button.\n\nUse this when pairing Button with routing links or other custom elements.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'asChild',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Visible button label or content.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'children',
        type: 'ReactNode | ReactElement',
        values: [],
      },
      {
        comments: 'Additional class names for custom styling.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'Icon shown after the button label.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'endIcon',
        type: 'ReactNode',
        values: [],
      },
      {
        comments:
          'Icon-only button content.\n\nFor buttons with text and an icon, use `startIcon` or `endIcon` instead.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'icon',
        type: 'ReactNode',
        values: [],
      },
      {
        comments:
          "Visual style that communicates the action's priority or outcome.",
        defaultValue: 'primary',
        displayName: 'Button',
        propName: 'intent',
        type: 'ButtonIntent',
        values: [
          'primary',
          'secondary',
          'tertiary',
          'constructive',
          'destructive',
        ],
      },
      {
        comments:
          'Shows a spinner while an action is in progress.\n\nAlso adds `aria-busy` for assistive technology.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'isBusy',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Size option for button spacing and text.',
        defaultValue: 'medium',
        displayName: 'Button',
        propName: 'size',
        type: 'ButtonSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Icon shown before the button label.',
        defaultValue: null,
        displayName: 'Button',
        propName: 'startIcon',
        type: 'ReactNode',
        values: [],
      },
      {
        comments:
          'Shows disabled styling without blocking interaction.\n\nUse this when the button should explain why an action is unavailable.',
        defaultValue: false,
        displayName: 'Button',
        propName: 'visuallyDisabled',
        type: 'boolean',
        values: [],
      },
    ],
    component: 'Button',
    importString: "import { Button } from '@themeshift/ui/components/Button';",
    slug: 'button',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Button',
  },
  {
    apiReference: [
      {
        comments:
          'Makes the checkbox wrapper span the full width of its container.',
        defaultValue: null,
        displayName: 'Checkbox',
        propName: 'fullWidth',
        type: 'boolean',
        values: [],
      },
      {
        comments:
          'Sets the checkbox to the mixed state.\n\nThis updates the DOM `indeterminate` property through JavaScript.',
        defaultValue: null,
        displayName: 'Checkbox',
        propName: 'indeterminate',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Visual size for the control.',
        defaultValue: null,
        displayName: 'Checkbox',
        propName: 'size',
        type: 'CheckboxSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Visual validation state for border and state colors.',
        defaultValue: null,
        displayName: 'Checkbox',
        propName: 'validationState',
        type: 'CheckboxValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
    ],
    component: 'Checkbox',
    importString:
      "import { Checkbox } from '@themeshift/ui/components/Checkbox';",
    slug: 'checkbox',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Checkbox',
  },
  {
    apiReference: [],
    component: 'ErrorMessage',
    importString:
      "import { ErrorMessage } from '@themeshift/ui/components/ErrorMessage';",
    slug: 'errormessage',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/ErrorMessage',
  },
  {
    apiReference: [
      {
        comments: 'Vertical alignment used when `layout="inline-control"`.',
        defaultValue: 'start',
        displayName: 'Field',
        propName: 'align',
        type: 'FieldAlign',
        values: ['start', 'center'],
      },
      {
        comments:
          'Field contents, usually a control and optional field subcomponents.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Helper text shown below the control.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'description',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Disables the control and related field content.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'disabled',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Validation message shown when the field is invalid.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'error',
        type: 'ReactNode',
        values: [],
      },
      {
        comments:
          'Whether label text should be visually hidden but still accessible.',
        defaultValue: false,
        displayName: 'Field',
        propName: 'hideLabel',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Optional stable ID base. If omitted, an ID is generated.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'id',
        type: 'string',
        values: [],
      },
      {
        comments: 'Visible label content for the control.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'label',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Layout style for control and supporting content.',
        defaultValue: 'stacked',
        displayName: 'Field',
        propName: 'layout',
        type: 'FieldLayout',
        values: ['stacked', 'inline-control'],
      },
      {
        comments: 'Marks the field as optional for presentation.',
        defaultValue: false,
        displayName: 'Field',
        propName: 'optional',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Makes the control read-only while keeping it focusable.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'readOnly',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Marks the control as required.',
        defaultValue: null,
        displayName: 'Field',
        propName: 'required',
        type: 'boolean',
        values: [],
      },
      {
        comments:
          'Sets the field validation state used for styling and accessibility.',
        defaultValue: 'none',
        displayName: 'Field',
        propName: 'validationState',
        type: 'ValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
      {
        comments: 'Helper text content associated with the control.',
        defaultValue: null,
        displayName: 'Field.Description',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Error text content associated with the control.',
        defaultValue: null,
        displayName: 'Field.Error',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments:
          'Keeps the error element mounted even when the field is not invalid. Useful for preventing layout shift and enabling show/hide transitions.',
        defaultValue: false,
        displayName: 'Field.Error',
        propName: 'forceMount',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Label text or custom label content.',
        defaultValue: null,
        displayName: 'Field.Label',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Overrides optional indicator rendering.',
        defaultValue: null,
        displayName: 'Field.Label',
        propName: 'showOptionalIndicator',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Overrides required indicator rendering.',
        defaultValue: null,
        displayName: 'Field.Label',
        propName: 'showRequiredIndicator',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Visually hides label text while keeping it accessible.',
        defaultValue: null,
        displayName: 'Field.Label',
        propName: 'visuallyHidden',
        type: 'boolean',
        values: [],
      },
    ],
    component: 'Field',
    importString: "import { Field } from '@themeshift/ui/components/Field';",
    slug: 'field',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Field',
  },
  {
    apiReference: [
      {
        comments: 'Semantic heading level to render.',
        defaultValue: 1,
        displayName: 'Heading',
        propName: 'level',
        type: 'HeadingLevel',
        values: [1, 2, 3, 4, 5, 6],
      },
      {
        comments: 'Applies the muted heading color treatment.',
        defaultValue: false,
        displayName: 'Heading',
        propName: 'muted',
        type: 'boolean',
        values: [],
      },
    ],
    component: 'Heading',
    importString:
      "import { Heading } from '@themeshift/ui/components/Heading';",
    slug: 'heading',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Heading',
  },
  {
    apiReference: [
      {
        comments: 'Decorative or functional content after the input.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'endAdornment',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Makes the input span the full width of its container.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'fullWidth',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Additional class name for the input element.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'inputClassName',
        type: 'string',
        values: [],
      },
      {
        comments: 'Visual size for the control.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'size',
        type: 'InputSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Decorative or functional content before the input.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'startAdornment',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Visual validation state for border and state colors.',
        defaultValue: null,
        displayName: 'Input',
        propName: 'validationState',
        type: 'InputValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
    ],
    component: 'Input',
    importString: "import { Input } from '@themeshift/ui/components/Input';",
    slug: 'input',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Input',
  },
  {
    apiReference: [],
    component: 'Label',
    importString: "import { Label } from '@themeshift/ui/components/Label';",
    slug: 'label',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Label',
  },
  {
    apiReference: [
      {
        comments:
          'Applies link styling to a child element instead of rendering an anchor.\n\nExample: `<Link asChild><NavLink to="/docs">Docs</NavLink></Link>`',
        defaultValue: null,
        displayName: 'Link',
        propName: 'asChild',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Link label or content.',
        defaultValue: null,
        displayName: 'Link',
        propName: 'children',
        type: 'React.ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the rendered element.',
        defaultValue: null,
        displayName: 'Link',
        propName: 'className',
        type: 'string',
        values: [],
      },
    ],
    component: 'Link',
    importString: "import { Link } from '@themeshift/ui/components/Link';",
    slug: 'link',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Link',
  },
  {
    apiReference: [
      {
        comments:
          'HTML element or component to render instead of the default element.',
        defaultValue: null,
        displayName: 'Navbar',
        propName: 'as',
        type: 'ElementType',
        values: [],
      },
      {
        comments: 'Navbar content.',
        defaultValue: null,
        displayName: 'Navbar',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the root element.',
        defaultValue: null,
        displayName: 'Navbar',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'CSS positioning mode for the navbar wrapper.',
        defaultValue: 'static',
        displayName: 'Navbar',
        propName: 'position',
        type: 'NavbarPosition',
        values: ['static', 'absolute', 'fixed', 'sticky'],
      },
      {
        comments:
          'HTML element or component to render instead of the default element.',
        defaultValue: null,
        displayName: 'Navbar.Container',
        propName: 'as',
        type: 'ElementType',
        values: [],
      },
      {
        comments: 'Container content.',
        defaultValue: null,
        displayName: 'Navbar.Container',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the container element.',
        defaultValue: null,
        displayName: 'Navbar.Container',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments:
          'Horizontal gap between container children.\n\nExample: `<Navbar.Container gap="2rem" />`',
        defaultValue: null,
        displayName: 'Navbar.Container',
        propName: 'gap',
        type: "CSSProperties['columnGap']",
        values: [],
      },
      {
        comments:
          'Maximum content width inside the navbar.\n\nExample: `<Navbar.Container maxWidth="72rem" />`',
        defaultValue: null,
        displayName: 'Navbar.Container',
        propName: 'maxWidth',
        type: "CSSProperties['maxWidth']",
        values: [],
      },
      {
        comments: 'Horizontal alignment inside the navbar row.',
        defaultValue: 'start',
        displayName: 'Navbar.Section',
        propName: 'align',
        type: 'NavbarSectionAlign',
        values: ['start', 'center', 'end'],
      },
      {
        comments:
          'HTML element or component to render instead of the default element.',
        defaultValue: null,
        displayName: 'Navbar.Section',
        propName: 'as',
        type: 'ElementType',
        values: [],
      },
      {
        comments: 'Section content.',
        defaultValue: null,
        displayName: 'Navbar.Section',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the section element.',
        defaultValue: null,
        displayName: 'Navbar.Section',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'Direction used to lay out section children.',
        defaultValue: 'row',
        displayName: 'Navbar.Section',
        propName: 'direction',
        type: 'NavbarSectionDirection',
        values: ['row', 'column'],
      },
      {
        comments:
          'Gap between section children.\n\nExample: `<Navbar.Section gap="0.75rem" />`',
        defaultValue: null,
        displayName: 'Navbar.Section',
        propName: 'gap',
        type: "CSSProperties['gap']",
        values: [],
      },
      {
        comments: 'Allows section items to wrap onto multiple lines.',
        defaultValue: false,
        displayName: 'Navbar.Section',
        propName: 'wrap',
        type: 'boolean',
        values: [],
      },
    ],
    component: 'Navbar',
    importString: "import { Navbar } from '@themeshift/ui/components/Navbar';",
    slug: 'navbar',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Navbar',
  },
  {
    apiReference: [
      {
        comments: '',
        defaultValue: null,
        displayName: 'Responsive',
        propName: 'as',
        type: 'ElementType',
        values: [],
      },
      {
        comments: 'Content that should be conditionally shown.',
        defaultValue: null,
        displayName: 'Responsive',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the rendered element.',
        defaultValue: null,
        displayName: 'Responsive',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'Breakpoint rule used to control visibility.',
        defaultValue: null,
        displayName: 'Responsive',
        propName: 'when',
        type: 'ResponsiveWhen',
        values: [],
      },
    ],
    component: 'Responsive',
    importString:
      "import { Responsive } from '@themeshift/ui/components/Responsive';",
    slug: 'responsive',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Responsive',
  },
  {
    apiReference: [
      {
        comments: 'Custom class name for the chevron icon container.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'chevronClassName',
        type: 'string',
        values: [],
      },
      {
        comments: 'Custom chevron icon. Defaults to `IconSelectChevron`.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'chevronIcon',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Makes the select span the full width of its container.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'fullWidth',
        type: 'boolean',
        values: [],
      },
      {
        comments:
          'Options to render when you do not want to pass children manually.\n\nWhen provided, `options` takes precedence over `children`.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'options',
        type: 'SelectOption[]',
        values: [],
      },
      {
        comments:
          'Placeholder label rendered as a disabled empty option.\n\nUse `defaultValue=""` or `value=""` to show it as the current value.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'placeholder',
        type: 'string',
        values: [],
      },
      {
        comments: 'Visual size for the control.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'size',
        type: 'SelectSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Visual validation state for border and state colors.',
        defaultValue: null,
        displayName: 'Select',
        propName: 'validationState',
        type: 'SelectValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
    ],
    component: 'Select',
    importString: "import { Select } from '@themeshift/ui/components/Select';",
    slug: 'select',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Select',
  },
  {
    apiReference: [
      {
        comments: 'Optional text content for the skip link.',
        defaultValue: null,
        displayName: 'SkipLink',
        propName: 'children',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class names to append to the rendered link.',
        defaultValue: null,
        displayName: 'SkipLink',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'Destination id reference, typically the main landmark.',
        defaultValue: null,
        displayName: 'SkipLink',
        propName: 'href',
        type: 'string',
        values: [],
      },
      {
        comments: 'Optional text label used when `children` is not provided.',
        defaultValue: null,
        displayName: 'SkipLink',
        propName: 'label',
        type: 'string',
        values: [],
      },
    ],
    component: 'SkipLink',
    importString:
      "import { SkipLink } from '@themeshift/ui/components/SkipLink';",
    slug: 'skiplink',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/SkipLink',
  },
  {
    apiReference: [
      {
        comments: '',
        defaultValue: null,
        displayName: 'Spinner',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: '',
        defaultValue: 24,
        displayName: 'Spinner',
        propName: 'size',
        type: 'number',
        values: [],
      },
    ],
    component: 'Spinner',
    importString:
      "import { Spinner } from '@themeshift/ui/components/Spinner';",
    slug: 'spinner',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Spinner',
  },
  {
    apiReference: [
      {
        comments: 'Makes the textarea span the full width of its container.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'fullWidth',
        type: 'boolean',
        values: [],
      },
      {
        comments: 'Maximum rows when `resize="auto"`.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'maxRows',
        type: 'number',
        values: [],
      },
      {
        comments: 'Minimum rows when `resize="auto"`.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'minRows',
        type: 'number',
        values: [],
      },
      {
        comments: 'Resize behavior for the control.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'resize',
        type: 'TextareaResize',
        values: ['none', 'vertical', 'horizontal', 'both', 'auto'],
      },
      {
        comments: 'Visual size for the control.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'size',
        type: 'TextareaSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Visual validation state for border and state colors.',
        defaultValue: null,
        displayName: 'Textarea',
        propName: 'validationState',
        type: 'TextareaValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
    ],
    component: 'Textarea',
    importString:
      "import { Textarea } from '@themeshift/ui/components/Textarea';",
    slug: 'textarea',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/Textarea',
  },
  {
    apiReference: [
      {
        comments: 'Additional class name for the outer wrapper.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'className',
        type: 'string',
        values: [],
      },
      {
        comments: 'Visual style used for the thumb color.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'intent',
        type: 'ToggleSwitchIntent',
        values: [
          'primary',
          'secondary',
          'tertiary',
          'constructive',
          'destructive',
        ],
      },
      {
        comments: 'Called with the next checked state after user interaction.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'onCheckedChange',
        type: '(checked: boolean) => void',
        values: [],
      },
      {
        comments: 'Size option for the track and thumb.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'size',
        type: 'ToggleSwitchSize',
        values: ['small', 'medium', 'large'],
      },
      {
        comments: 'Additional class name for the thumb element.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'thumbClassName',
        type: 'string',
        values: [],
      },
      {
        comments: 'Icon shown inside the thumb when the switch is off.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'thumbIconOff',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Icon shown inside the thumb when the switch is on.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'thumbIconOn',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Additional class name for the track element.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'trackClassName',
        type: 'string',
        values: [],
      },
      {
        comments: 'Icon shown inside the track when the switch is off.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'trackIconOff',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Icon shown inside the track when the switch is on.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'trackIconOn',
        type: 'ReactNode',
        values: [],
      },
      {
        comments: 'Visual validation state for border feedback.',
        defaultValue: null,
        displayName: 'ToggleSwitch',
        propName: 'validationState',
        type: 'ToggleSwitchValidationState',
        values: ['none', 'invalid', 'valid', 'warning'],
      },
    ],
    component: 'ToggleSwitch',
    importString:
      "import { ToggleSwitch } from '@themeshift/ui/components/ToggleSwitch';",
    slug: 'toggleswitch',
    sourceCodeUrl:
      'https://github.com/themeshift-dev/themeshift/tree/develop/packages/ui/src/components/ToggleSwitch',
  },
] satisfies ComponentData[];
