name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release PR or GitHub releases
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.AUTOMATION_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: main

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs['packages/cli--release_created'] == 'true' || steps.release.outputs['packages/core--release_created'] == 'true' || steps.release.outputs['packages/ui--release_created'] == 'true' || steps.release.outputs['packages/vite-plugin--release_created'] == 'true' }}
        with:
          version: 10.18.0

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs['packages/cli--release_created'] == 'true' || steps.release.outputs['packages/core--release_created'] == 'true' || steps.release.outputs['packages/ui--release_created'] == 'true' || steps.release.outputs['packages/vite-plugin--release_created'] == 'true' }}
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs['packages/cli--release_created'] == 'true' || steps.release.outputs['packages/core--release_created'] == 'true' || steps.release.outputs['packages/ui--release_created'] == 'true' || steps.release.outputs['packages/vite-plugin--release_created'] == 'true' }}

      - run: pnpm build
        if: ${{ steps.release.outputs['packages/cli--release_created'] == 'true' || steps.release.outputs['packages/core--release_created'] == 'true' || steps.release.outputs['packages/ui--release_created'] == 'true' || steps.release.outputs['packages/vite-plugin--release_created'] == 'true' }}

      - name: Publish @themeshift/cli
        if: ${{ steps.release.outputs['packages/cli--release_created'] == 'true' }}
        run: pnpm --filter @themeshift/cli publish --access public --no-git-checks

      - name: Publish @themeshift/core
        if: ${{ steps.release.outputs['packages/core--release_created'] == 'true' }}
        run: pnpm --filter @themeshift/core publish --access public --no-git-checks

      - name: Publish @themeshift/ui
        if: ${{ steps.release.outputs['packages/ui--release_created'] == 'true' }}
        run: pnpm --filter @themeshift/ui publish --access public --no-git-checks

      - name: Publish @themeshift/vite-plugin
        if: ${{ steps.release.outputs['packages/vite-plugin--release_created'] == 'true' }}
        run: pnpm --filter @themeshift/vite-plugin publish --access public --no-git-checks
